### ISSUE TITLE
Support toggling the display of approved PRS

### ISSUE THREAD

**Issue by id0Sch** [NitaiPerez/stash-notify#3]
I would like to view the pr's that iv'e already approved in the list

**Comment by selfish** [comment]
Expected in upcoming version 4.0.0

**Comment by id0Sch** [comment]
Eta?

On Wednesday, June 22, 2016, Nitai J. Perez notifications@github.com
wrote:

> Expected in upcoming version 4.0.0
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/CommonRaven/stash-notify/issues/3#issuecomment-227796100,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFl9RH2H2JFlWkqnzK-ZqOg8BEvKYqdZks5qOV_DgaJpZM4I78-Q
> .

## 

Ido Schachter
Software developer
[image: ironSource] http://www.ironsrc.com

email ido.schachter@ironsrc.com
mobile +972-52-605-2282
fax +972-77-5448273
28 Lilienblum St., Tel Aviv
ironsrc.com http://www.ironsrc.com
[image: linkedin] https://www.linkedin.com/company/ironsource [image:
twitter] https://twitter.com/ironsource [image: facebook]
https://www.facebook.com/ironSource [image: googleplus]
https://plus.google.com/+ironsrc
This email (including any attachments) is for the sole use of the intended
recipient and may contain confidential information which may be protected
by legal privilege. If you are not the intended recipient, or the employee
or agent responsible for delivering it to the intended recipient, you are
hereby notified that any use, dissemination, distribution or copying of
this communication and/or its content is strictly prohibited. If you are
not the intended recipient, please immediately notify us by reply email or
by telephone, delete this email and destroy any copies. Thank you.

**Comment by selfish** [comment]
With a bit of luck under 2 weeks, but no promises at this stage. :)

**Comment by selfish** [comment]
Update: It looks like Stash does not provide an endpoint for PRs which were approved but not merged, so this isn't going to be implemented in v4.0.0 as expected. If such an endpoint is found, please share it and I will add the functionality. Pull requests are also welcome.

**Comment by selfish** [comment]
Switching status to won't fix. Currently seems impossible in stash.
