### ISSUE TITLE
Support latest butbucket API.

### ISSUE THREAD

**Issue by bibmaster** [NitaiPerez/stash-notify#8]
It would be great to have an option for API switch.
The only difference is API prefix - 
new: /rest/api/latest/inbox/pull-requests
old: /rest/inbox/latest/pull-requests

**Comment by selfish** [comment]
@bibmaster - will you create a PR?

**Comment by bibmaster** [comment]
Yes, i'll try.
I am C++, not JS developer, so don't be too keen.

**Comment by selfish** [comment]
Don't sweat it then, I'll do it myself.
Will take some time though as I'm a bittt occupied ATM.

If you're able to get it done, I'll merge and deploy, If not, I will soon myself.

**Comment by bibmaster** [comment]
Done. There was some bug with default config initialization during extension setup, all fields were uninitialized, can't explain why. Separated functions for parameters change and initialization solved the problem.

**Comment by selfish** [comment]
Released in v3.1.6
